### ISSUE TITLE
submit mario-less en cash

### ISSUE THREAD

**Issue by kimdebie** [uva/cs50x#87]
Mario-less en cash hebben allebei nog geen submit-form.

**Comment by stgm** [comment]
Ja klopt ja, wordt donderdag gefikst. cc @WouterVrielink @hnstr

**Comment by WouterVrielink** [comment]
@stgm is dit niet een kwestie van zorgen dat in de submit.yml geen gelijke waardes staat voor name? Want dan kan ik dit wel oplossen.

**Comment by stgm** [comment]
Ik wilde even overleggen of dit niet onder dezelfde naam gesubmit moet worden. Leek mij ook handig. Dus eerst ff overleg ;-)

**Comment by WouterVrielink** [comment]
Check.

**Comment by stgm** [comment]
Aangepast in lijn met Wouter's suggestie
